// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connection(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['Connection']['Connection'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Execute(arg1) {
  return window['go']['services']['Connection']['Execute'](arg1);
}
